name: Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: pip install pylint
    - run: pylint --disable=C0304 --disable=C0114 hello.py
    - run: python hello.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: my-python-script
        path: hello.py